### ISSUE TITLE
maintainers

### ISSUE THREAD

**Issue by ExFlo** [dot-build/angular-serve-and-run#2]
Hi @darlanalves 
You seems to be the only maintainers of dot-build/angular-serve-and-run. We intend to use it to run some playwright testing. As we are going to publish with Microsoft a schematic to add playwright to an angular project (that will use your builder), we may expect more usage of your npm package. This is why I am contacting you, we would like if possible either to know if you intend to maintain the package (security…), or if you are willing to add some of us (Amadeus devs who are already doing open-source project like ng-bootstrap) as maintainers in order to help you with it ?
Thx a lot

**Comment by darlanalves** [comment]
@ExFlo I added you to a team in this org to collaborate.
Thanks for your interest 🙂
